import { SystemSettings } from "@/types/system-settings.types";

export const mockSystemSettings: SystemSettings = {
  general:  {
    platformName: "Aeon Community",
    platformDescription: "Community management platform for leaders and members",
    timezone: "Africa/Johannesburg",
    dateFormat: "DD/MM/YYYY",
    timeFormat: "24h",
    language: "en",
    maintenanceMode: false,
    maintenanceMessage: "We're currently performing scheduled maintenance. Please check back soon.",
  },
  security: {
    minPasswordLength: 8,
    requireUppercase: true,
    requireLowercase: true,
    requireNumbers: true,
    requireSpecialChars: true,
    passwordExpiryDays: 90,
    preventPasswordReuse: 5,
    sessionTimeout: 60,
    maxConcurrentSessions:  3,
    twoFactorRequired: false,
    twoFactorGracePeriodDays:  7,
    maxLoginAttempts:  5,
    lockoutDuration:  30,
    ipWhitelistEnabled: false,
    ipWhitelist: [],
    ipBlacklistEnabled: true,
    ipBlacklist: ["185.220.101.0/24", "45.155.205.0/24"],
  },
  notifications: {
    emailProvider: "smtp",
    smtpHost: "smtp.example.com",
    smtpPort:  587,
    smtpUsername:  "notifications@aeon.com",
    smtpSecure: true,
    fromEmail: "no-reply@aeon.com",
    fromName: "Aeon Community",
    replyToEmail: "support@aeon.com",
    emailNotificationsEnabled: true,
    welcomeEmailEnabled: true,
    passwordResetEmailEnabled: true,
    eventReminderEmailEnabled: true,
    eventApprovalEmailEnabled:  true,
    taskAssignmentEmailEnabled: true,
    weeklyDigestEnabled: false,
  },
  appearance: {
    primaryColor: "#8B5CF6",
    secondaryColor: "#3B82F6",
    accentColor:  "#10B981",
    darkModeDefault:  true,
    allowUserThemeToggle: true,
    showPoweredBy: false,
    loginWelcomeText:  "Welcome back to your community",
    footerText: "© 2025 Aeon Community. All rights reserved.",
    footerLinks: [
      { label: "Privacy Policy", url: "/privacy" },
      { label: "Terms of Service", url: "/terms" },
      { label: "Support", url: "/support" },
    ],
  },
  events: {
    requireApproval:  true,
    autoApproveForLeaders: false,
    maxAttendeesDefault:  50,
    allowWaitlist: true,
    reminderHoursBefore: [24, 2],
    allowEventComments: true,
    allowEventRatings: true,
    eventCategories:  [
      { id: "meeting", name: "Meeting", color: "#3B82F6" },
      { id: "workshop", name: "Workshop", color: "#8B5CF6" },
      { id: "social", name: "Social", color: "#EC4899" },
      { id: "training", name: "Training", color: "#F59E0B" },
      { id: "conference", name: "Conference", color: "#10B981" },
      { id: "other", name: "Other", color: "#6B7280" },
    ],
  },
  members:  {
    allowSelfRegistration: false,
    requireEmailVerification: true,
    requireAdminApproval: true,
    defaultRole: "member",
    profileFieldsRequired: ["firstName", "lastName", "email", "phone"],
    allowProfileEditing: true,
    showMemberDirectory: true,
    allowMemberSearch: true,
  },
  integrations: {
    googleCalendarEnabled: false,
    outlookCalendarEnabled:  false,
    slackEnabled: false,
    teamsEnabled: false,
    googleAnalyticsEnabled: false,
    storageProvider: "local",
  },
  backups: {
    autoBackupEnabled: true,
    backupFrequency: "daily",
    backupTime: "02:00",
    backupRetentionDays: 30,
    backupLocation: "local",
    lastBackupAt: "2025-01-01T02:00:00Z",
    lastBackupSize: "2. 4 GB",
    lastBackupStatus:  "success",
  },
};

export const timezones = [
  { value: "Africa/Johannesburg", label: "South Africa (SAST)" },
  { value: "Africa/Lagos", label: "Nigeria (WAT)" },
  { value: "Africa/Nairobi", label: "Kenya (EAT)" },
  { value:  "Africa/Cairo", label: "Egypt (EET)" },
  { value:  "Europe/London", label:  "UK (GMT/BST)" },
  { value: "Europe/Paris", label: "Central Europe (CET)" },
  { value: "America/New_York", label: "US Eastern (EST/EDT)" },
  { value: "America/Los_Angeles", label: "US Pacific (PST/PDT)" },
  { value: "Asia/Dubai", label: "UAE (GST)" },
  { value: "Asia/Singapore", label: "Singapore (SGT)" },
  { value: "Australia/Sydney", label:  "Australia Eastern (AEST)" },
];

export const dateFormats = [
  { value:  "DD/MM/YYYY", label:  "DD/MM/YYYY (31/12/2025)" },
  { value: "MM/DD/YYYY", label: "MM/DD/YYYY (12/31/2025)" },
  { value:  "YYYY-MM-DD", label: "YYYY-MM-DD (2025-12-31)" },
  { value: "DD MMM YYYY", label: "DD MMM YYYY (31 Dec 2025)" },
  { value: "MMM DD, YYYY", label:  "MMM DD, YYYY (Dec 31, 2025)" },
];

export const languages = [
  { value: "en", label: "English" },
  { value: "af", label: "Afrikaans" },
  { value:  "zu", label: "Zulu" },
  { value: "xh", label: "Xhosa" },
  { value: "fr", label: "French" },
  { value: "pt", label: "Portuguese" },
];