import { Event } from "@/types/event.types";

export const mockAdminEventApprovals: Event[] = [
  {
    id: "EVT-101",
    title: "Team Building Workshop",
    description: "Interactive activities to build team spirit and communication.",
    category: "workshop",
    startDate: "2025-01-20T14:00:00Z",
    endDate: "2025-01-20T17:00:00Z",
    location: "Main Hall, Aeon HQ",
    isVirtual: false,
    status: "pending_approval",
    visibility: "public",
    requiresRegistration: true,
    maxAttendees: 30,
    currentAttendees: 19,
    createdBy: "user_01",
    createdByUser: {
      id: "user_01",
      displayName: "Linda van Rooyen",
      avatarUrl: "",
      initials: "LR",
    },
    createdAt: "2024-12-28T10:15:00Z",
    updatedAt: "2024-12-28T10:15:00Z",
  },
  {
    id: "EVT-102",
    title: "Monthly Meetup",
    description: "Regular community update and networking event.",
    category: "meeting",
    startDate: "2025-01-28T18:00:00Z",
    endDate: "2025-01-28T20:00:00Z",
    location: "Conference Room B",
    isVirtual: false,
    status: "approved",
    visibility: "members_only",
    requiresRegistration: true,
    maxAttendees: 50,
    currentAttendees: 45,
    createdBy: "user_02",
    createdByUser: {
      id: "user_02",
      displayName: "Jacob Mensah",
      avatarUrl: "",
      initials: "JM",
    },
    approvedBy: "Admin",
    approvedAt: "2024-12-29T09:00:00Z",
    createdAt: "2024-12-27T08:00:00Z",
    updatedAt: "2024-12-29T09:00:00Z",
  },
  {
    id: "EVT-103",
    title: "Volunteer Induction",
    description: "Intro session for new volunteers. Mandatory attendance.",
    category: "training",
    startDate: "2025-01-25T12:00:00Z",
    endDate: "2025-01-25T14:00:00Z",
    isVirtual: true,
    virtualLink: "https://meet.aeon/volunteerInduction",
    status: "rejected",
    visibility: "invite_only",
    requiresRegistration: true,
    maxAttendees: 20,
    currentAttendees: 11,
    createdBy: "user_03",
    createdByUser: {
      id: "user_03",
      displayName: "Anele Sithole",
      avatarUrl: "",
      initials: "AS",
    },
    rejectionReason: "Insufficient details provided",
    createdAt: "2024-12-26T14:40:00Z",
    updatedAt: "2024-12-28T12:00:00Z",
  },
  {
    id: "EVT-104",
    title: "Social Night",
    description: "Fun and games—unwind after a busy week.",
    category: "social",
    startDate: "2025-01-30T19:00:00Z",
    endDate: "2025-01-30T22:30:00Z",
    isVirtual: false,
    status: "pending_approval",
    visibility: "public",
    requiresRegistration: false,
    currentAttendees: 0,
    createdBy: "user_04",
    createdByUser: {
      id: "user_04",
      displayName: "Sipho Dlamini",
      avatarUrl: "",
      initials: "SD",
    },
    createdAt: "2024-12-29T16:00:00Z",
    updatedAt: "2024-12-29T16:00:00Z",
  },
];

// Stats for the event approvals module
export const approvalStats = [
  {
    title: "Pending Events",
    value: mockAdminEventApprovals.filter(e => e.status === "pending_approval").length,
    change: "+2 this week",
    changeType: "neutral",
    icon: require("lucide-react").Clock,
    iconColor: "bg-amber-500/10 text-amber-400",
  },
  {
    title: "Approved Events",
    value: mockAdminEventApprovals.filter(e => e.status === "approved").length,
    change: "+1 approved",
    changeType: "positive",
    icon: require("lucide-react").CheckCircle2,
    iconColor: "bg-emerald-500/10 text-emerald-400",
  },
  {
    title: "Rejected",
    value: mockAdminEventApprovals.filter(e => e.status === "rejected").length,
    change: "",
    changeType: "negative",
    icon: require("lucide-react").XCircle,
    iconColor: "bg-red-500/10 text-red-400",
  },
  {
    title: "Total Submitted",
    value: mockAdminEventApprovals.length,
    change: "",
    changeType: "neutral",
    icon: require("lucide-react").Calendar,
    iconColor: "bg-blue-500/10 text-blue-400",
  },
];