import { AdminUser, LoginActivity, UserActivityLog, SystemRole, AccountStatus, ROLE_PERMISSIONS } from "@/types/admin-user.types";

/**
 * Mock admin users - single community platform
 */
export const mockAdminUsers: AdminUser[] = [
  {
    id: "usr_001",
    email:  "sarah.admin@aeon.com",
    firstName:  "Sarah",
    lastName: "Mitchell",
    displayName: "Sarah Mitchell",
    initials:  "SM",
    avatarUrl: "",
    phone: "+27 82 123 4567",
    role: "admin",
    permissions:  ROLE_PERMISSIONS. admin,
    customPermissions: false,
    status: "active",
    twoFactorStatus:  "enabled",
    passwordLastChanged: "2024-11-15T10:00:00Z",
    mustChangePassword: false,
    failedLoginAttempts:  0,
    lastLoginAt: "2025-01-01T08:30:00Z",
    lastActiveAt: "2025-01-01T09:45:00Z",
    loginCount: 234,
    createdAt: "2023-01-15T00:00:00Z",
    updatedAt: "2024-12-20T14:00:00Z",
    notes: "Primary administrator for the platform.",
    tags: ["primary", "verified"],
  },
  {
    id:  "usr_002",
    email: "james.admin@aeon.com",
    firstName: "James",
    lastName: "Van Der Berg",
    displayName: "James Van Der Berg",
    initials: "JV",
    phone: "+27 83 456 7890",
    role:  "admin",
    permissions: ROLE_PERMISSIONS.admin,
    customPermissions: false,
    status: "active",
    twoFactorStatus: "enabled",
    passwordLastChanged: "2024-10-20T14:00:00Z",
    mustChangePassword: false,
    failedLoginAttempts: 0,
    lastLoginAt: "2024-12-31T16:20:00Z",
    lastActiveAt:  "2024-12-31T17:00:00Z",
    loginCount: 178,
    createdAt: "2023-02-20T00:00:00Z",
    updatedAt: "2024-12-15T09:00:00Z",
    tags: ["senior"],
  },
  {
    id:  "usr_003",
    email: "linda.leader@aeon.com",
    firstName:  "Linda",
    lastName: "Van Rooyen",
    displayName: "Linda Van Rooyen",
    initials:  "LR",
    phone:  "+27 84 567 8901",
    role: "community_leader",
    permissions: ROLE_PERMISSIONS.community_leader,
    customPermissions: false,
    status: "active",
    twoFactorStatus:  "enabled",
    passwordLastChanged: "2024-09-15T10:00:00Z",
    mustChangePassword: false,
    failedLoginAttempts: 0,
    lastLoginAt: "2024-12-30T09:15:00Z",
    lastActiveAt:  "2024-12-30T11:30:00Z",
    loginCount: 89,
    createdAt: "2023-04-10T00:00:00Z",
    updatedAt: "2024-11-20T16:00:00Z",
    notes: "Senior community leader.  Handles most event coordination.",
    tags: ["senior", "events"],
  },
  {
    id: "usr_004",
    email:  "thabo.leader@aeon.com",
    firstName:  "Thabo",
    lastName: "Mokoena",
    displayName: "Thabo Mokoena",
    initials: "TM",
    phone: "+27 85 678 9012",
    role:  "community_leader",
    permissions:  ROLE_PERMISSIONS. community_leader,
    customPermissions:  false,
    status: "active",
    twoFactorStatus: "disabled",
    mustChangePassword: false,
    failedLoginAttempts: 0,
    lastLoginAt: "2024-12-28T14:00:00Z",
    lastActiveAt: "2024-12-28T15:45:00Z",
    loginCount: 67,
    createdAt: "2023-06-15T00:00:00Z",
    updatedAt: "2024-10-05T11:00:00Z",
  },
  {
    id: "usr_005",
    email: "priya.leader@aeon.com",
    firstName:  "Priya",
    lastName: "Naidoo",
    displayName: "Priya Naidoo",
    initials: "PN",
    phone: "+27 86 789 0123",
    role: "community_leader",
    permissions: {
      ... ROLE_PERMISSIONS.community_leader,
      events_approve: true,
    },
    customPermissions: true,
    status:  "active",
    twoFactorStatus: "enabled",
    passwordLastChanged:  "2024-12-01T09:00:00Z",
    mustChangePassword: false,
    failedLoginAttempts: 0,
    lastLoginAt: "2024-12-29T10:30:00Z",
    lastActiveAt:  "2024-12-29T12:15:00Z",
    loginCount: 112,
    createdAt: "2023-07-20T00:00:00Z",
    updatedAt: "2024-12-10T14:30:00Z",
    notes: "Has elevated permissions to approve events.",
    tags: ["elevated", "trusted"],
  },
  {
    id: "usr_006",
    email:  "jacob.mod@aeon.com",
    firstName:  "Jacob",
    lastName: "Mensah",
    displayName: "Jacob Mensah",
    initials: "JM",
    role: "moderator",
    permissions:  ROLE_PERMISSIONS. moderator,
    customPermissions: false,
    status:  "active",
    twoFactorStatus: "disabled",
    mustChangePassword: false,
    failedLoginAttempts: 0,
    lastLoginAt: "2024-12-27T08:00:00Z",
    lastActiveAt: "2024-12-27T09:30:00Z",
    loginCount: 45,
    createdAt: "2023-09-01T00:00:00Z",
    updatedAt: "2024-09-15T10:00:00Z",
  },
  {
    id: "usr_007",
    email: "anele.pending@aeon.com",
    firstName:  "Anele",
    lastName: "Sithole",
    displayName: "Anele Sithole",
    initials:  "AS",
    role: "community_leader",
    permissions:  ROLE_PERMISSIONS.community_leader,
    customPermissions: false,
    status: "pending",
    twoFactorStatus: "disabled",
    mustChangePassword: true,
    failedLoginAttempts:  0,
    loginCount: 0,
    createdAt: "2024-12-20T00:00:00Z",
    updatedAt: "2024-12-20T00:00:00Z",
    notes:  "New community leader.  Awaiting first login.",
    tags: ["new"],
  },
  {
    id:  "usr_008",
    email: "michael.suspended@aeon.com",
    firstName:  "Michael",
    lastName: "Johnson",
    displayName: "Michael Johnson",
    initials:  "MJ",
    role: "community_leader",
    permissions: ROLE_PERMISSIONS.community_leader,
    customPermissions: false,
    status: "suspended",
    statusReason: "Violation of community guidelines - pending investigation",
    statusChangedAt: "2024-12-15T00:00:00Z",
    statusChangedBy: "Sarah Mitchell",
    twoFactorStatus:  "enabled",
    mustChangePassword: false,
    failedLoginAttempts: 0,
    lastLoginAt: "2024-12-14T16:00:00Z",
    loginCount: 34,
    createdAt: "2024-02-01T00:00:00Z",
    updatedAt: "2024-12-15T00:00:00Z",
    tags: ["investigation"],
  },
  {
    id:  "usr_009",
    email: "emma.locked@aeon.com",
    firstName:  "Emma",
    lastName: "Davis",
    displayName: "Emma Davis",
    initials:  "ED",
    role: "community_leader",
    permissions: ROLE_PERMISSIONS.community_leader,
    customPermissions: false,
    status: "locked",
    statusReason: "Too many failed login attempts",
    statusChangedAt: "2024-12-30T10:00:00Z",
    twoFactorStatus:  "disabled",
    mustChangePassword: true,
    failedLoginAttempts:  5,
    lockedUntil:  "2024-12-30T11:00:00Z",
    lastLoginAt: "2024-12-29T15:00:00Z",
    loginCount: 23,
    createdAt: "2024-05-10T00:00:00Z",
    updatedAt: "2024-12-30T10:00:00Z",
  },
  {
    id: "usr_010",
    email: "david.viewer@aeon.com",
    firstName:  "David",
    lastName: "Brown",
    displayName: "David Brown",
    initials:  "DB",
    role: "viewer",
    permissions:  ROLE_PERMISSIONS.viewer,
    customPermissions: false,
    status:  "active",
    twoFactorStatus: "disabled",
    mustChangePassword: false,
    failedLoginAttempts: 0,
    lastLoginAt: "2024-12-25T12:00:00Z",
    lastActiveAt: "2024-12-25T12:30:00Z",
    loginCount: 12,
    createdAt: "2024-08-15T00:00:00Z",
    updatedAt: "2024-08-15T00:00:00Z",
    notes: "External auditor with view-only access.",
    tags: ["auditor", "external"],
  },
  {
    id: "usr_011",
    email: "sophie.deactivated@aeon. com",
    firstName: "Sophie",
    lastName: "Taylor",
    displayName: "Sophie Taylor",
    initials:  "ST",
    role: "community_leader",
    permissions: ROLE_PERMISSIONS.community_leader,
    customPermissions: false,
    status: "deactivated",
    statusReason: "User requested account deletion",
    statusChangedAt: "2024-11-01T00:00:00Z",
    statusChangedBy: "James Van Der Berg",
    twoFactorStatus: "disabled",
    mustChangePassword: false,
    failedLoginAttempts: 0,
    lastLoginAt: "2024-10-28T09:00:00Z",
    loginCount: 56,
    createdAt: "2023-11-20T00:00:00Z",
    updatedAt: "2024-11-01T00:00:00Z",
  },
];

/**
 * Mock login activity
 */
export const mockLoginActivity: LoginActivity[] = [
  {
    id: "log_1",
    timestamp:  "2025-01-01T08:30:00Z",
    ipAddress: "102.65.123.45",
    location: "Johannesburg, South Africa",
    device:  "MacBook Pro",
    browser: "Chrome 120",
    status: "success",
  },
  {
    id: "log_2",
    timestamp: "2024-12-31T16:20:00Z",
    ipAddress: "102.65.123.45",
    location:  "Johannesburg, South Africa",
    device: "MacBook Pro",
    browser: "Chrome 120",
    status:  "success",
  },
  {
    id:  "log_3",
    timestamp: "2024-12-30T09:15:00Z",
    ipAddress: "41.203.67.89",
    location:  "Cape Town, South Africa",
    device: "iPhone 15",
    browser: "Safari Mobile",
    status:  "success",
  },
  {
    id: "log_4",
    timestamp: "2024-12-30T09:10:00Z",
    ipAddress: "41.203.67.89",
    location: "Cape Town, South Africa",
    device: "iPhone 15",
    browser: "Safari Mobile",
    status:  "failed",
    failureReason:  "Invalid password",
  },
  {
    id:  "log_5",
    timestamp: "2024-12-29T14:00:00Z",
    ipAddress: "196.25.45.123",
    location:  "Durban, South Africa",
    device: "Windows PC",
    browser:  "Edge 120",
    status: "blocked",
    failureReason: "Account locked",
  },
];

/**
 * Mock user activity log
 */
export const mockUserActivityLog: UserActivityLog[] = [
  {
    id:  "act_1",
    userId: "usr_001",
    action: "User Login",
    details:  "Successful login from Johannesburg, South Africa",
    ipAddress:  "102.65.123.45",
    timestamp: "2025-01-01T08:30:00Z",
  },
  {
    id: "act_2",
    userId: "usr_003",
    action:  "Event Created",
    details:  "Created event: Team Building Workshop",
    timestamp: "2024-12-28T10:15:00Z",
  },
  {
    id: "act_3",
    userId: "usr_001",
    action:  "User Suspended",
    details:  "Suspended user: Michael Johnson (usr_008)",
    timestamp: "2024-12-15T00:00:00Z",
    performedBy: {
      id: "usr_001",
      displayName: "Sarah Mitchell",
    },
  },
  {
    id: "act_4",
    userId: "usr_002",
    action:  "Role Changed",
    details: "Changed role from viewer to community_leader",
    timestamp: "2024-12-10T14:30:00Z",
    performedBy: {
      id: "usr_001",
      displayName: "Sarah Mitchell",
    },
  },
  {
    id: "act_5",
    userId: "usr_005",
    action: "Permissions Modified",
    details: "Granted custom permission: events_approve",
    timestamp: "2024-12-10T14:30:00Z",
    performedBy: {
      id: "usr_001",
      displayName: "Sarah Mitchell",
    },
  },
];

/**
 * Get role display info
 */
export function getRoleBadge(role:  SystemRole): {
  variant: "success" | "warning" | "info" | "neutral" | "danger";
  label: string;
} {
  const config = {
    admin: { variant: "danger" as const, label: "Admin" },
    community_leader: { variant: "success" as const, label:  "Community Leader" },
    moderator:  { variant: "info" as const, label: "Moderator" },
    viewer: { variant: "neutral" as const, label: "Viewer" },
  };
  return config[role];
}

/**
 * Get status display info
 */
export function getStatusBadge(status: AccountStatus): {
  variant: "success" | "warning" | "danger" | "neutral" | "info";
  label: string;
} {
  const config = {
    active: { variant: "success" as const, label: "Active" },
    pending: { variant:  "warning" as const, label: "Pending" },
    suspended: { variant:  "danger" as const, label: "Suspended" },
    locked: { variant:  "danger" as const, label: "Locked" },
    deactivated: { variant: "neutral" as const, label: "Deactivated" },
  };
  return config[status];
}

/**
 * Get 2FA status display info
 */
export function getTwoFactorBadge(status: AdminUser["twoFactorStatus"]): {
  variant: "success" | "warning" | "neutral";
  label: string;
} {
  const config = {
    enabled: { variant: "success" as const, label:  "Enabled" },
    enforced: { variant:  "success" as const, label: "Enforced" },
    disabled: { variant: "neutral" as const, label: "Disabled" },
  };
  return config[status];
}