export const mockAccessRequests = [
  {
    id: "REQ-001",
    name: "Thabo Mabaso",
    email: "thabo.mabaso@example.com",
    phone: "+27 82 456 7890",
    organization: "Tech Innovators SA",
    role: "Developer",
    requestedAccess: "User",
    status: "pending",
    submittedAt: "2024-12-29T08:30:00",
    reason: "Need access to collaborate on community projects and attend tech meetups",
    avatar: "TM",
  },
  {
    id: "REQ-002",
    name: "Naledi Khumalo",
    email: "naledi.k@startup.co.za",
    phone: "+27 71 234 5678",
    organization: "StartUp Hub",
    role: "Product Manager",
    requestedAccess: "Leader",
    status: "pending",
    submittedAt: "2024-12-29T07:15:00",
    reason: "Looking to organize and lead entrepreneurship workshops for the community",
    avatar: "NK",
  },
  {
    id: "REQ-003",
    name: "Jacob Mensah",
    email: "jacob.m@marketing.com",
    phone: "+27 83 987 6543",
    organization: "Digital Marketing Co",
    role: "Marketing Lead",
    requestedAccess: "User",
    status: "pending",
    submittedAt: "2024-12-29T06:45:00",
    reason: "Want to join marketing team discussions and events",
    avatar: "JM",
  },
  {
    id: "REQ-004",
    name: "Anele Sithole",
    email: "anele.sithole@tech.io",
    phone: "+27 84 123 4567",
    organization: "Tech Solutions",
    role: "Software Engineer",
    requestedAccess: "User",
    status: "approved",
    submittedAt: "2024-12-28T14:20:00",
    approvedAt: "2024-12-28T15:30:00",
    approvedBy: "Sarah Johnson",
    reason: "Interested in tech community events and networking",
    avatar: "AS",
  },
  {
    id: "REQ-005",
    name: "Linda van Rooyen",
    email: "linda.vr@events.co.za",
    phone: "+27 72 345 6789",
    organization: "Event Masters",
    role: "Event Coordinator",
    requestedAccess: "Leader",
    status: "rejected",
    submittedAt: "2024-12-28T11:00:00",
    rejectedAt: "2024-12-28T16:45:00",
    rejectedBy: "Michael Lee",
    rejectionReason: "Insufficient verification documents provided",
    reason: "Want to organize large-scale community events",
    avatar: "LR",
  },
  {
    id: "REQ-006",
    name: "Sipho Dlamini",
    email: "sipho.d@design.studio",
    phone: "+27 81 765 4321",
    organization: "Creative Studio",
    role: "UX Designer",
    requestedAccess: "User",
    status: "pending",
    submittedAt: "2024-12-27T16:30:00",
    reason: "Looking to connect with other designers and share knowledge",
    avatar: "SD",
  },
];