import { Event } from "@/types/event.types";

export const mockAdminEventApprovals: Event[] = [
  {
    id: "EVT-101",
    title: "Team Building Workshop",
    description: "Interactive activities to build team spirit and communication. This full-day workshop includes trust exercises, problem-solving challenges, and collaborative games designed to strengthen interpersonal relationships within teams.",
    category: "workshop",
    startDate: "2025-01-20T14:00:00Z",
    endDate: "2025-01-20T17:00:00Z",
    location: "Main Hall, Aeon HQ",
    isVirtual: false,
    status: "pending_approval",
    visibility: "public",
    requiresRegistration: true,
    maxAttendees: 30,
    currentAttendees: 19,
    createdBy: "user_01",
    createdByUser: {
      id: "user_01",
      displayName: "Linda van Rooyen",
      avatarUrl: "",
      initials: "LR",
    },
    createdAt: "2024-12-28T10:15:00Z",
    updatedAt: "2024-12-28T10:15:00Z",
  },
  {
    id: "EVT-102",
    title: "Monthly Meetup",
    description: "Regular community update and networking event. Join us for project updates, community announcements, and an opportunity to connect with fellow members over refreshments.",
    category: "meeting",
    startDate: "2025-01-28T18:00:00Z",
    endDate: "2025-01-28T20:00:00Z",
    location: "Conference Room B",
    isVirtual: false,
    status: "approved",
    visibility: "members_only",
    requiresRegistration: true,
    maxAttendees: 50,
    currentAttendees: 45,
    createdBy: "user_02",
    createdByUser: {
      id: "user_02",
      displayName: "Jacob Mensah",
      avatarUrl: "",
      initials: "JM",
    },
    approvedBy: "Admin",
    approvedAt: "2024-12-29T09:00:00Z",
    createdAt: "2024-12-27T08:00:00Z",
    updatedAt: "2024-12-29T09:00:00Z",
  },
  {
    id: "EVT-103",
    title: "Volunteer Induction",
    description: "Intro session for new volunteers. Mandatory attendance for all newly registered volunteers. We'll cover community guidelines, expectations, and available opportunities.",
    category: "training",
    startDate: "2025-01-25T12:00:00Z",
    endDate: "2025-01-25T14:00:00Z",
    isVirtual: true,
    virtualLink: "https://meet.aeon/volunteerInduction",
    status: "rejected",
    visibility: "invite_only",
    requiresRegistration: true,
    maxAttendees: 20,
    currentAttendees: 11,
    createdBy: "user_03",
    createdByUser: {
      id: "user_03",
      displayName: "Anele Sithole",
      avatarUrl: "",
      initials: "AS",
    },
    rejectionReason: "Insufficient details provided. Please include a detailed agenda and list of facilitators.",
    createdAt: "2024-12-26T14:40:00Z",
    updatedAt: "2024-12-28T12:00:00Z",
  },
  {
    id: "EVT-104",
    title: "Social Night",
    description: "Fun and games—unwind after a busy week. Join us for board games, music, and snacks. A great opportunity to relax and get to know other community members in a casual setting.",
    category: "social",
    startDate: "2025-01-30T19:00:00Z",
    endDate: "2025-01-30T22:30:00Z",
    isVirtual: false,
    location: "Community Lounge, Building A",
    status: "pending_approval",
    visibility: "members_only",
    requiresRegistration: true,
    maxAttendees: 40,
    currentAttendees: 0,
    createdBy: "user_04",
    createdByUser: {
      id: "user_04",
      displayName: "Thabo Mokoena",
      avatarUrl: "",
      initials: "TM",
    },
    createdAt: "2024-12-30T09:00:00Z",
    updatedAt: "2024-12-30T09:00:00Z",
  },
  {
    id: "EVT-105",
    title: "Tech Talk: AI in 2025",
    description: "Expert panel discussion on the future of AI and its impact on our industry. Featuring guest speakers from leading tech companies.  Q&A session included.",
    category: "conference",
    startDate: "2025-02-05T15:00:00Z",
    endDate: "2025-02-05T17:30:00Z",
    isVirtual: true,
    virtualLink: "https://zoom.us/j/987654321",
    status: "pending_approval",
    visibility: "public",
    requiresRegistration: true,
    maxAttendees: 100,
    currentAttendees: 0,
    createdBy: "user_05",
    createdByUser: {
      id: "user_05",
      displayName: "Priya Naidoo",
      avatarUrl: "",
      initials: "PN",
    },
    createdAt: "2024-12-31T11:30:00Z",
    updatedAt: "2024-12-31T11:30:00Z",
  },
  {
    id: "EVT-106",
    title: "Leadership Development Program",
    description: "Six-week intensive program for emerging leaders. Topics include strategic thinking, team management, communication skills, and conflict resolution.",
    category: "training",
    startDate: "2025-02-10T09:00:00Z",
    endDate: "2025-02-10T16:00:00Z",
    isVirtual: false,
    location: "Executive Training Center",
    status: "approved",
    visibility: "invite_only",
    requiresRegistration: true,
    maxAttendees: 25,
    currentAttendees: 22,
    createdBy: "user_01",
    createdByUser: {
      id: "user_01",
      displayName: "Linda van Rooyen",
      avatarUrl: "",
      initials: "LR",
    },
    approvedBy: "Admin",
    approvedAt: "2024-12-20T14:00:00Z",
    createdAt: "2024-12-15T10:00:00Z",
    updatedAt: "2024-12-20T14:00:00Z",
  },
  {
    id: "EVT-107",
    title: "Quarterly Review Meeting",
    description: "Review of Q4 achievements and Q1 planning session. All department heads required to attend. Agenda will be shared 48 hours prior.",
    category: "meeting",
    startDate: "2025-01-15T10:00:00Z",
    endDate: "2025-01-15T12:00:00Z",
    isVirtual: true,
    virtualLink: "https://teams.microsoft.com/l/meeting/q4review",
    status: "approved",
    visibility: "members_only",
    requiresRegistration: false,
    currentAttendees: 15,
    createdBy: "user_02",
    createdByUser: {
      id: "user_02",
      displayName: "Jacob Mensah",
      avatarUrl: "",
      initials: "JM",
    },
    approvedBy: "Admin",
    approvedAt: "2024-12-28T08:00:00Z",
    createdAt: "2024-12-25T16:00:00Z",
    updatedAt: "2024-12-28T08:00:00Z",
  },
  {
    id: "EVT-108",
    title: "Photography Workshop",
    description: "Learn the basics of photography from professional photographers. Bring your own camera or smartphone. All skill levels welcome.",
    category: "workshop",
    startDate: "2025-02-15T13:00:00Z",
    endDate: "2025-02-15T16:00:00Z",
    isVirtual: false,
    location: "Creative Studio, Floor 3",
    status: "draft",
    visibility: "public",
    requiresRegistration: true,
    maxAttendees: 20,
    currentAttendees: 0,
    createdBy: "user_06",
    createdByUser: {
      id: "user_06",
      displayName: "Michelle Chen",
      avatarUrl: "",
      initials: "MC",
    },
    createdAt: "2025-01-01T09:00:00Z",
    updatedAt: "2025-01-01T09:00:00Z",
  },
];

// Mock attendees for admin events
export const mockAdminEventAttendees = [
  {
    id: "att_101",
    eventId: "EVT-101",
    userId: "user_10",
    user: {
      id: "user_10",
      displayName: "Sarah Williams",
      email: "sarah.w@example.com",
      initials: "SW",
      phone: "+27 82 123 4567",
    },
    status: "registered" as const,
    registeredAt: "2024-12-29T10:00:00Z",
  },
  {
    id: "att_102",
    eventId: "EVT-101",
    userId: "user_11",
    user: {
      id: "user_11",
      displayName: "Michael Johnson",
      email: "m.johnson@example.com",
      initials: "MJ",
    },
    status: "checked_in" as const,
    registeredAt: "2024-12-29T11:00:00Z",
    checkedInAt: "2025-01-20T13:55:00Z",
    checkedInBy: "Admin",
  },
  {
    id: "att_103",
    eventId: "EVT-101",
    userId: "user_12",
    user: {
      id: "user_12",
      displayName: "Emma Davis",
      email: "emma.d@example.com",
      initials: "ED",
    },
    status: "registered" as const,
    registeredAt: "2024-12-30T09:00:00Z",
  },
  {
    id: "att_104",
    eventId: "EVT-102",
    userId: "user_13",
    user: {
      id: "user_13",
      displayName: "James Wilson",
      email: "j.wilson@example.com",
      initials: "JW",
    },
    status: "checked_in" as const,
    registeredAt: "2024-12-28T14:00:00Z",
    checkedInAt: "2025-01-28T17:50:00Z",
    checkedInBy: "Admin",
  },
  {
    id: "att_105",
    eventId: "EVT-102",
    userId: "user_14",
    user: {
      id: "user_14",
      displayName: "Olivia Brown",
      email: "o.brown@example.com",
      initials: "OB",
    },
    status: "cancelled" as const,
    registeredAt: "2024-12-28T15:00:00Z",
  },
  {
    id: "att_106",
    eventId: "EVT-106",
    userId: "user_15",
    user: {
      id: "user_15",
      displayName: "Daniel Lee",
      email: "d.lee@example.com",
      initials: "DL",
      phone: "+27 83 456 7890",
    },
    status: "registered" as const,
    registeredAt: "2024-12-21T10:00:00Z",
  },
  {
    id: "att_107",
    eventId: "EVT-106",
    userId: "user_16",
    user: {
      id: "user_16",
      displayName: "Sophie Taylor",
      email: "s.taylor@example.com",
      initials: "ST",
    },
    status: "no_show" as const,
    registeredAt: "2024-12-22T11:00:00Z",
  },
];